password_file /mosquitto/config/passwd

listener 1883
allow_anonymous false

listener 8083
protocol websockets
allow_anonymous false

listener 9883
protocol http_api
http_dir /usr/share/mosquitto/dashboard
allow_anonymous true
