services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: file-watcher-mosquitto
    ports:
      - "1883:1883"
      - "9883:9883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
